// <auto-generated />
using System;
using FlashHackForum.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashHackForum.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountFavorites", b =>
                {
                    b.Property<int>("AccountUserId")
                        .HasColumnType("int");

                    b.Property<int>("FavoritesForumThreadID")
                        .HasColumnType("int");

                    b.HasKey("AccountUserId", "FavoritesForumThreadID");

                    b.HasIndex("FavoritesForumThreadID");

                    b.ToTable("AccountFavorites");
                });

            modelBuilder.Entity("FlashHackForum.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime>("AccountCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AccountRating")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowAdvertisements")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowContact")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowToCompanies")
                        .HasColumnType("bit");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FlashHackForum.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("FlashHackForum.Models.Competens", b =>
                {
                    b.Property<int>("CompetensId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetensId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompetensId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Competenses");
                });

            modelBuilder.Entity("FlashHackForum.Models.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LengthOfEducation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearEnded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearStarted")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducationId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("FlashHackForum.Models.ForumThread", b =>
                {
                    b.Property<int>("ForumThreadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForumThreadID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShowSignature")
                        .HasColumnType("bit");

                    b.Property<int>("SecondCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ForumThreadID");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SecondCategoryId");

                    b.ToTable("ForumThreads");
                });

            modelBuilder.Entity("FlashHackForum.Models.MainCategory", b =>
                {
                    b.Property<int>("MainCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MainCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MainCategoryId");

                    b.ToTable("MainCategories");
                });

            modelBuilder.Entity("FlashHackForum.Models.SecondCategory", b =>
                {
                    b.Property<int>("SecondCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecondCategoryId"));

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SecondCategoryId");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("SecondCategories");
                });

            modelBuilder.Entity("FlashHackForum.Models.ThreadPost", b =>
                {
                    b.Property<int>("ThreadPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreadPostId"));

                    b.Property<bool>("Anonymous")
                        .HasColumnType("bit");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("int");

                    b.Property<int>("ForumThreadId")
                        .HasColumnType("int");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("PostCreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplyToPostId")
                        .HasColumnType("int");

                    b.Property<bool>("ShowSignature")
                        .HasColumnType("bit");

                    b.HasKey("ThreadPostId");

                    b.HasIndex("ForumThreadId");

                    b.HasIndex("PostCreatorId");

                    b.HasIndex("ReplyToPostId");

                    b.ToTable("ThreadPosts");
                });

            modelBuilder.Entity("FlashHackForum.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FlashHackForum.Models.UserCompetence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("CompetensId")
                        .HasColumnType("int");

                    b.Property<int?>("EducationId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CompetensId");

                    b.HasIndex("EducationId");

                    b.ToTable("UserCompetences");
                });

            modelBuilder.Entity("FlashHackForum.Models.UserPostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ReactionType")
                        .HasColumnType("int");

                    b.Property<int>("ThreadPostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThreadPostId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPostReactions");
                });

            modelBuilder.Entity("AccountFavorites", b =>
                {
                    b.HasOne("FlashHackForum.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlashHackForum.Models.ForumThread", null)
                        .WithMany()
                        .HasForeignKey("FavoritesForumThreadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlashHackForum.Models.Account", b =>
                {
                    b.HasOne("FlashHackForum.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("FlashHackForum.Models.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashHackForum.Models.Competens", b =>
                {
                    b.HasOne("FlashHackForum.Models.Company", null)
                        .WithMany("CompetensesToLookFor")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("FlashHackForum.Models.ForumThread", b =>
                {
                    b.HasOne("FlashHackForum.Models.Account", "ThreadCreator")
                        .WithMany("ThreadsStarted")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlashHackForum.Models.SecondCategory", "SecondCategory")
                        .WithMany("Threads")
                        .HasForeignKey("SecondCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecondCategory");

                    b.Navigation("ThreadCreator");
                });

            modelBuilder.Entity("FlashHackForum.Models.SecondCategory", b =>
                {
                    b.HasOne("FlashHackForum.Models.MainCategory", "MainCategory")
                        .WithMany("SecondCategories")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("FlashHackForum.Models.ThreadPost", b =>
                {
                    b.HasOne("FlashHackForum.Models.ForumThread", "ForumThread")
                        .WithMany("PostsInThread")
                        .HasForeignKey("ForumThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashHackForum.Models.Account", "PostCreator")
                        .WithMany("ThreadPosts")
                        .HasForeignKey("PostCreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashHackForum.Models.ThreadPost", "ReplyToPost")
                        .WithMany()
                        .HasForeignKey("ReplyToPostId");

                    b.Navigation("ForumThread");

                    b.Navigation("PostCreator");

                    b.Navigation("ReplyToPost");
                });

            modelBuilder.Entity("FlashHackForum.Models.UserCompetence", b =>
                {
                    b.HasOne("FlashHackForum.Models.Account", "Account")
                        .WithMany("UserCompetences")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashHackForum.Models.Competens", "Competens")
                        .WithMany()
                        .HasForeignKey("CompetensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashHackForum.Models.Education", "Education")
                        .WithMany()
                        .HasForeignKey("EducationId");

                    b.Navigation("Account");

                    b.Navigation("Competens");

                    b.Navigation("Education");
                });

            modelBuilder.Entity("FlashHackForum.Models.UserPostReaction", b =>
                {
                    b.HasOne("FlashHackForum.Models.ThreadPost", "ThreadPost")
                        .WithMany("Reactions")
                        .HasForeignKey("ThreadPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlashHackForum.Models.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThreadPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlashHackForum.Models.Account", b =>
                {
                    b.Navigation("ThreadPosts");

                    b.Navigation("ThreadsStarted");

                    b.Navigation("UserCompetences");
                });

            modelBuilder.Entity("FlashHackForum.Models.Company", b =>
                {
                    b.Navigation("CompetensesToLookFor");
                });

            modelBuilder.Entity("FlashHackForum.Models.ForumThread", b =>
                {
                    b.Navigation("PostsInThread");
                });

            modelBuilder.Entity("FlashHackForum.Models.MainCategory", b =>
                {
                    b.Navigation("SecondCategories");
                });

            modelBuilder.Entity("FlashHackForum.Models.SecondCategory", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("FlashHackForum.Models.ThreadPost", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("FlashHackForum.Models.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
